apiVersion: v1
kind: Secret
metadata:
  name: fcg-secrets
type: Opaque
stringData:
  Jwt__Key: "TWluaGFDaGF2ZVN1cGVyU2VjcmV0YURvSldUMTIzNDU2IQ==" 
  ConnectionStrings__FcgDb: "Host=users-db;Port=5432;Database=usersdb;Username=admin;Password=password123"
  ConnectionStrings__CatalogDb: "Host=catalog-db;Port=5432;Database=catalogdb;Username=admin;Password=password123"
  ConnectionStrings__PaymentDb: "Host=payments-db;Port=5432;Database=paymentsdb;Username=admin;Password=password123"