apiVersion: v1
kind: Secret
metadata:
  name: fcg-secrets
type: Opaque
stringData:
  Jwt__Key: "TWluaGFDaGF2ZVN1cGVyU2VjcmV0YURvSldUMTIzNDU2IQ==" 
  ConnectionStrings__UsersDb: "Host=host.docker.internal;Port=5432;Database=usersdb;Username=admin;Password=password123"
  ConnectionStrings__CatalogDb: "Host=host.docker.internal;Port=5433;Database=catalogdb;Username=admin;Password=password123"
  ConnectionStrings__PaymentsDb: "Host=host.docker.internal;Port=5434;Database=paymentsdb;Username=admin;Password=password123"